DROP TABLE IF EXISTS CLIENT;  

CREATE TABLE CLIENT (  
	id INT AUTO_INCREMENT  PRIMARY KEY,  
	shared_key VARCHAR(50) NOT NULL,  
	bussiness_id VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	data_added DATE NOT NULL  
); 